<a href="https://colab.research.google.com/github/TonyQ2k3/pytorch-training/blob/main/notebooks/pytorch_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is Pytorch?

Pytorch is an open-source machine learning library for Python. It's primarily used for deep learning and other AI-related field.

Some key features of Pytorch includes:
+ Efficient GPU integration
+ Optimized tensor computation library

In [7]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu121


## What is a Tensor?

A tensor is a generalization of vectors and matrices. It's basically 1-to-n dimension array.

Tensors can be created using `torch.tensor()`

In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor1 = tensor1.reshape((3, 1))
print(tensor1)

tensor([[1],
        [2],
        [3]])


In [ ]:
tensor1 = torch.tensor([1, 2, 3, 4, 5, 6])
tensor1 = tensor1.reshape((2, 3))
print(tensor1)

## Random tensors
Generating tensors by hand is inefficient, that's why we create tensors of random values. The model will look into the data and update it to represent the data better later on.

As a ML engineer, you will decide how the model starts it's tensor (initialization), looks into data (representation) and updates tensor (optimize).

In [ ]:
# Generate a random tensor
tensor = torch.rand(3, 3)
tensor

tensor([[0.7908, 0.6044, 0.6083],
        [0.1823, 0.0200, 0.2399],
        [0.6781, 0.4277, 0.5878]])

In [ ]:
# Generate 3D tensor
tensor = torch.rand(3, 3, 3)
tensor

In [ ]:
# Generate random int tensor
tensor = torch.randint(0, 100, size=(3, 3))
tensor

## Zeros and ones tensor

In [ ]:
# Generate tensor of zeros
tensor = torch.zeros(size=(3, 3, 3), dtype=torch.int32)
tensor

In [ ]:
# Generate tensor of ones
tensor = torch.ones(size=(3, 3), dtype=torch.int32)
tensor

In [ ]:
tensor = torch.arange(1, 101, 1)
tensor = tensor.reshape((10, 10))
tensor

tensor([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Extracting information from a tensor
+ Get data types from tensors: `tensor.dtype`
+ Get tensor shape: `tensor.shape`
+ Get tensor device; `tensor.device`




## Tensor operations

In [6]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6]).reshape((3, 1))

multiply = torch.matmul(tensor_a, tensor_b)
multiply

tensor([32])

## Tensor min, max, aggregation

In [17]:
tensor = torch.randint(low=0, high=100, size=(20,))
print("Tensor: ", tensor)
print("Max value", tensor.max())
print("Max value index", tensor.argmax())
print("Min value", tensor.min())
print("Min value index", tensor.argmin())

Tensor:  tensor([72,  4, 17, 64, 28, 78, 31, 32, 26, 25, 88,  0,  9,  4, 88, 10,  4, 94,
        18, 97])
Max value tensor(97)
Max value index tensor(19)
Min value tensor(0)
Min value index tensor(11)


In [15]:
print("Mean value", torch.mean(tensor, dtype=torch.float32))

Mean value tensor(46.1000)


In [16]:
print("Sum value", torch.sum(tensor))

Sum value tensor(922)
